packages:
  - apps/*
  - packages/*
minimumReleaseAge: 1440
overrides:
  deepmerge-ts: 8.0.1
  mysql2: 3.22.0
allowBuilds:
  '@prisma/engines': true
  prisma: true
  sharp: true
  esbuild: true
  msgpackr-extract: false
  unrs-resolver: true
