import type { ProviderType } from "./catalog";

export interface WebhookSetupGuide {
  title: string;
  steps: string[];
  events: string[];
  eventLabel?: string;
  note?: string;
  docsUrl?: string;
}

export function webhookSetupGuide(
  type: ProviderType,
  settings: { messageStreamType?: string } = {},
): WebhookSetupGuide {
  switch (type) {
    case "resend":
      return {
        title: "Resend webhook setup",
        steps: [
          "In Resend, open Webhooks and add a webhook.",
          "Paste the EmailBlast webhook URL shown above.",
          "Enable the email events listed below, save the webhook, then copy Resend's signing secret back into EmailBlast.",
        ],
        events: [
          "email.sent",
          "email.delivered",
          "email.delivery_delayed",
          "email.bounced",
          "email.complained",
          "email.failed",
          "email.opened",
          "email.clicked",
        ],
        note: "Contact, domain, scheduled and inbound events are not needed for campaign delivery status.",
        docsUrl: "https://resend.com/docs/dashboard/webhooks/introduction",
      };
    case "ses":
      return {
        title: "Amazon SES delivery notifications",
        steps: [
          "Create or choose one Amazon SNS topic in the same SES region.",
          "On the verified SES identity, publish Delivery, Bounce and Complaint notifications to that topic.",
          "Subscribe the EmailBlast webhook URL to the SNS topic, then paste the exact topic ARN into EmailBlast.",
        ],
        events: ["Delivery", "Bounce", "Complaint"],
        note: "EmailBlast's current SES callback path uses authenticated SNS identity notifications. Open and click event publishing is not required for delivery confirmation.",
        docsUrl: "https://docs.aws.amazon.com/ses/latest/dg/configure-sns-notifications.html",
      };
    case "mailgun":
      return {
        title: "Mailgun webhook setup",
        steps: [
          "Open the sending domain in Mailgun and configure its webhooks.",
          "Use the EmailBlast webhook URL for the delivery events below.",
          "Copy Mailgun's webhook signing key into EmailBlast.",
        ],
        events: [
          "accepted",
          "delivered",
          "temporary_fail",
          "permanent_fail",
          "complained",
          "unsubscribed",
          "opened",
          "clicked",
        ],
        docsUrl: "https://documentation.mailgun.com/docs/mailgun/user-manual/webhooks/webhooks",
      };
    case "sendgrid":
      return {
        title: "SendGrid Event Webhook",
        steps: [
          "Open SendGrid Event Webhook settings and paste the EmailBlast URL as the Post URL.",
          "Enable the events below.",
          "Enable Signed Event Webhook verification and paste SendGrid's public verification key into EmailBlast.",
        ],
        events: [
          "processed",
          "delivered",
          "deferred",
          "bounce",
          "dropped",
          "spam report",
          "unsubscribe",
          "open",
          "click",
        ],
        note: "Open and click callbacks require SendGrid tracking to be enabled.",
        docsUrl: "https://www.twilio.com/docs/sendgrid/for-developers/tracking-events/getting-started-event-webhook",
      };
    case "brevo":
      return {
        title: "Brevo transactional webhook",
        steps: [
          "Create a transactional webhook in Brevo and paste the EmailBlast webhook URL.",
          "Enable the email events below.",
          "Configure HTTP Basic authentication with username emailsystem and the callback secret generated by EmailBlast.",
        ],
        events: [
          "Sent",
          "Deferred",
          "Delivered",
          "Soft Bounced",
          "Hard Bounced",
          "Spam",
          "Invalid Email",
          "Blocked",
          "Error",
          "Unsubscribed",
          "Opened",
          "Clicked",
        ],
        docsUrl: "https://developers.brevo.com/docs/transactional-webhooks",
      };
    case "postmark": {
      const broadcast = settings.messageStreamType !== "transactional";
      return {
        title: "Postmark webhook setup",
        steps: [
          "Open the Postmark Message Stream used by this connection and add a webhook.",
          "Paste the EmailBlast webhook URL and select the available events below.",
          "Configure HTTP Basic authentication with username emailsystem and the callback secret generated by EmailBlast.",
        ],
        events: broadcast
          ? ["Delivery", "Open", "Click", "Subscription Change"]
          : [
              "Delivery",
              "Bounce",
              "Spam Complaint",
              "Open",
              "Click",
              "Subscription Change",
            ],
        note: broadcast
          ? "Postmark does not offer Bounce or Spam Complaint modular webhooks on Broadcast Message Streams."
          : undefined,
        docsUrl: "https://postmarkapp.com/developer/webhooks/webhooks-overview",
      };
    }
    case "mailjet":
      return {
        title: "Mailjet event tracking",
        steps: [
          "Open Mailjet Event Tracking and register the EmailBlast URL.",
          "Enable the events below.",
          "Use HTTP Basic authentication with username emailsystem and the callback secret generated by EmailBlast.",
        ],
        events: ["sent", "bounce", "blocked", "spam", "unsub", "open", "click"],
        note: "Open and click events require the corresponding Mailjet tracking settings.",
        docsUrl: "https://dev.mailjet.com/docs/email-api/webhooks/webhooks-overview",
      };
    case "smtp2go":
      return {
        title: "SMTP2GO webhook setup",
        steps: [
          "Open SMTP2GO Settings → Webhooks and add the EmailBlast URL.",
          "Choose JSON output where available and enable the email events below.",
          "Use Basic authentication with username emailsystem and the callback secret generated by EmailBlast.",
        ],
        events: [
          "processed",
          "delivered",
          "bounce",
          "reject",
          "spam",
          "unsubscribe",
          "open",
          "click",
        ],
        docsUrl: "https://developers.smtp2go.com/docs/setup-a-webhook",
      };
    case "elastic":
      return {
        title: "Elastic Email notifications",
        steps: [
          "Open Elastic Email notification settings and use the EmailBlast URL as the notification URL.",
          "Append ?key=YOUR_SECRET to that URL, using the callback secret generated by EmailBlast.",
          "Enable the notification types below.",
        ],
        events: [
          "Sent",
          "Bounce / Error",
          "Complaints",
          "Unsubscribed",
          "Opened",
          "Clicked",
        ],
        note: "Treat the full URL containing the key as a credential. Notification availability can depend on the Elastic Email plan.",
        docsUrl: "https://help.elasticemail.com/en/articles/4804685-notification-settings",
      };
    case "smtp":
      return {
        title: "Custom SMTP delivery callbacks",
        steps: [
          "Plain SMTP does not provide final delivery callbacks by itself.",
          "Check the company that provides your SMTP account for Webhooks, Events, Delivery notifications or callbacks.",
          "If it supports them, point those callbacks to the EmailBlast URL and use HTTP Basic username emailsystem with the generated callback secret.",
        ],
        events: [
          "accepted / processed",
          "delivered",
          "deferred / temporary failure",
          "bounce / permanent failure",
          "complaint / spam",
          "unsubscribe",
          "open",
          "click",
        ],
        eventLabel: "Useful events when your SMTP service offers them",
        note: "EmailBlast accepts common event/status, messageId/message_id, recipient/email/to, timestamp/time/date and optional attemptId fields. A different payload format needs a provider-specific adapter.",
      };
    case "mock":
      return {
        title: "Development callback",
        steps: ["Development Mock is for local verification only."],
        events: [],
      };
  }
}
